# Generated by Django 4.2.11 on 2024-03-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_apartmentuserform_message_userform_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentuserform',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('connected', 'connected'), ('pending', 'Pending')], default=('new', 'new'), max_length=10),
        ),
        migrations.AddField(
            model_name='userform',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('connected', 'connected'), ('pending', 'Pending')], default=('new', 'new'), max_length=10),
        ),
    ]
